### ISSUE TITLE
MT4 server data 수신 및 저장 방법 숙지

### ISSUE THREAD

**Issue by fbpasia** [fbpasia/kjgloviceFX#20]

**Comment by richardKim-glovice** [comment]
https://support.metaquotes.net/en/docs/mt4/api/webservices_api/web_api_example

here is the content on the link above: 


Example: Quotes on a Website
The section features an example of a simple informer with quotes. You can download a zip with the example files at the link. To get started, you only need to unzip the files to the website directory on the server.

File Descriptions
•quotes.php - an informer of quotes of symbols EURUSD, GBPUSD, USDJPY, AUDUSD, USDCAD. The file contains:

•configuration parameters for connecting to the server (IP address, port)

•request caching parameters

•The function of sending requests to the server, with an implemented support for result catching

•example.php - an example of a web page containing the informer quotes.php.

•cache - directory for storing the cache of results

•img - a directory with images that are used for displaying quotes.

Adjustable Parameters
Request parameters are set using the PHP define function:

// Address of the MetaTrader server
define('T_HOST','www.metaquotes.ru'); 

The values of the following parameters are defined at the beginning of the quotes.php file:

•T_HOST - MetaTrader server address. Example: "www.metaquotes.ru".

•T_PORT - MetaTrader server port. Example: 443.

•T_TIMEOUT - MetaTrader server connection timeout in seconds. Example: 5.

•T_QUOTES - list of symbols to be published. Example: "EURUSD,GBPUSD,USDJPY,AUDUSD,USDCAD,".

•T_CACHEDIR - directory to store cache files. Example: "c:/temp/" or "cache/".

•T_CACHETIME - cache expiry time in seconds. Example: 5.

•T_CLEAR_DELNUMBER - the number of files closed at a time, reaching which the process of cache clearing should be stopped. Example: 15.

The values ​​of these parameters can be changed at your discretion.

**Comment by richardKim-glovice** [comment]
example.php
This file is a simple HTML page with a built-in informer.

<html>
<head>
  <title>Quotes publish example</title>
</head>
<body>
  <center>
  Quotes informer:
  <?include('quotes.php')?>
  </center>
</body>
</html>

**Comment by richardKim-glovice** [comment]
Here is the quote.php
Please be aware I have changed it to quote.txt. 

[quote.txt](https://github.com/fbpasia/kjgloviceFX/files/4357507/quote.txt)
